services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ./ollama:/root/.ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    ports:
      - $OLLAMA_PORT:11434
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
