---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  Nome_Utente: 
    disabled: false
    displayname: "Nome Cognome"
    password: "$argon2id$v=19$m=65536,t=3,p=xxxxxxxxx" #genera con il comando "docker run authelia/authelia:latest authelia crypto hash generate argon2 --password 'password_scelta'"
    email: nome_utente@yourdomain.tld
    groups:
      - admins
      - dev