services:
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    restart: unless-stopped
    volumes:
      - /var/log:/var/log:ro
      - ./data:/data
      - $DOCKER_VOLUMES/nextcloud_aio_nextcloud/_data/data:$DOCKER_VOLUMES/nextcloud_aio_nextcloud/_data/data:ro #nextcloud
      - $DOCKERS_DIR/homeassistant/config:$DOCKERS_DIR/homeassistant/config:ro #homeassistant
    network_mode: host
    cap_add:
    - NET_ADMIN
    - NET_RAW
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    logging:
      driver: "syslog"
      options:
        tag: "Vaultwarden"
