networks:
  plex_docked:
    external: true

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
#      - 1900:1900/udp #disattivato visto che lo utilizza home assistant (verificare)
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp 
    environment:
      - TZ=$TZ
      - PLEX_CLAIM=$PLEX_CLAIM
      - ADVERTISE_IP=http://$HOST_IP:32400/
    hostname: plex.$YOURDOMAIN #personalizzabile
    volumes:
      - ./config:/config
#      - <path/to/transcode/temp>:/transcode # consigliabile utilizzare ssd?
      - ./Libreria:/data # magari spostare
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
