version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - $DOCKERS_DIR/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - $SURVEILLANCE_DIR:/mnt/videosorveglianza:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
