[API_KEYS]
OPENAI = ""
GROQ = ""
ANTHROPIC = ""
GEMINI = ""

[API_ENDPOINTS]
OLLAMA = "http://192.168.0.100:11434"
SEARXNG = "http://192.168.0.100:18080"

[GENERAL]
PORT = 3100
SIMILARITY_MEASURE = "cosine"
KEEP_ALIVE = "5m"
