services:
  perplexica-backend:
    container_name: perplexica-backend
    build:
      context: .
      dockerfile: backend.dockerfile
    image: itzcrazykns1337/perplexica-backend:main
    environment:
      - SEARXNG_API_URL=http://$HOST_IP:$SEARXNG_PORT
    # depends_on:
    #   - searxng
    ports:
      - 3001:3001
    volumes:
      - ./backend-dbstore:/home/perplexica/data
      - ./uploads:/home/perplexica/uploads
      - ./config.toml:/home/perplexica/config.toml
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - perplexica-network
    restart: unless-stopped

  perplexica-frontend:
    container_name: perplexica-frontend
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://$HOST_IP:3001/api
        - NEXT_PUBLIC_WS_URL=ws://$HOST_IP:3001
    image: itzcrazykns1337/perplexica-frontend:main
    depends_on:
      - perplexica-backend
    ports:
      - $PERPLEXICA_PORT:3000
    networks:
      - perplexica-network
    # environment:
    #   - NEXT_PUBLIC_API_URL=http://$HOST_IP:3001/api
    #   - NEXT_PUBLIC_WS_URL=ws://$HOST_IP:3001
    restart: unless-stopped

networks:
  perplexica-network:
     name: perplexica-network

# volumes:
#   backend-dbstore:
#   uploads: