# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
homeassistant:
    external_url: "https://ha.yourdomain.tld" #sostituire yourdomain.tld con il proprio dominio
    media_dirs:
        videosorveglianza: "/mnt/videosorveglianza"
    packages: !include_dir_named packages