services:
  duplicati:
    image: linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=0
      - PGID=0
      - TZ=$TZ
      - CLI_ARGS= #optional
    volumes:
      - ./config:/config
#      - $BACKUP_REPOSITORY/duplicati:/backups
      - /:/source:ro
    ports:
      - 8200:8200
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
